### ISSUE TITLE
Question: figuring this out as I go, could use a little guidence on this step: add 'kubebuilder CRD Markers'

### ISSUE THREAD

**Issue by karezza** [cert-manager/sample-external-issuer#22]
I have a very short bash and powershell script which I currently use to generate certificates in my kubernetes cluster, they are so small and simple that it seems like if I can just get the sample issuer customized I should be able to add what little code is needed to create a working issuer for my environment which I could then share and support for the community.

Could I get just a little more detail on this step?  I see the comment it is specifying '// +kubebuilder:subresource:status' is already in the file its asking me to modify.  Is that what I need to add?  Has it already been added automatically and the documentation just needs to be updated?  Do I need to add in multiple places?  Just looking for a little guidence.  Please don't just give me a link to https://book.kubebuilder.io/reference/markers/crd.html, I saw the link and have clicked on it, thank you ahead of time.  Maybe the answer is I need to go off and learn go for a couple months.  If so I let me know and I can move on till I have time.  Was hoping I might be able to learn *just enough* to get things going for now.

```
api/v1alpha1/{cluster}issuer_types.go: Add Kubebuilder CRD Markers to allow modification of IssuerStatus as a Status Subresource: 
// +kubebuilder:subresource:status
```

**Comment by wallrj** [comment]
@karezza It looks like newer versions of `kubebuilder` add the subresource:status annotation by default. See:
 * https://github.com/kubernetes-sigs/kubebuilder/pull/1484

I wrote this guide using an earlier version of `kubebuilder`.

So the instructions and the `kubebuilder` version needs updating.
